language: python

python:
  - 3.6

env:
  global:
    # Doctr deploy key for drdoctr/travis-ci-com-testing
    - secure: "6CJcy9YO+ftCyafX3C+x0jKLAfF0OimKyvZXO/eMamcoBOon+BCsryL6qCvuXg1g3eKz61k83Edjn5Nizl2uOscjc5OFU7zqEtIYVKMNtXbLV55Id3ANeM9esLXjQx1XKrrd1ngYR9T8KA83Y72C7g/4YPWW+1rO2wmvdtOBkMr6g0oAGAYlEUMcFI9cgPb70NR0R4iG3OHWOFfy4bffKxRlcu8siEzP8O1/Lk3EbknHVKyHdUR/uliCUwvJNcOQqSDYDnQWiFeNqzCgbsB7DIU0y2hCM9qAmSA2THCE9jSCcIiUwSqdKruEP+2LGKFYkIXf4FIPDswhPApk4WH4C7+Jsam2MnG23IjZ0LVHQXM6W3Aj94OJTk5Tkk8f8EZOTQXp+EeBGSb6PGj6RTgytImpjJXnSjeBfWKJfNl74VB5jqKpiUH9691334xOpJKNOjjmlvh8l0A6fvjx92oAnuab6H/I58IuJle3pMADgiW+JECkXjcUmDGOD4oUc/vch+GMxMoh0CvwOa0QrE9YxCUpZ5XkFwJ4u5KwX2/E4HR+PA8+FhuSxz2C/10l19+0S5HJrznEk9OMruLeRT4PhHG9KzxAWhICJ4M+XVicbfuWkzvzuSXKDjnGjjfy+1kuDMmayLsp3Puh79JUgl7QuU3Ht36tx0kCzt1WfuP8fww="


script:
  - set -e
  - pip install doctr
  - doctr deploy --built-docs test-html/ .
