language: python

python:
  - 3.6

env:
  global:
    # Doctr deploy key for drdoctr/travis-ci-com-testing
    - secure: "RqOBJJ7LQESRwS1sXfnZdDQSyRoWvM/FC03ROjutdcwy2obBd/RJ4X0TLWTpK00f7BCXNbxEt7Hbz6XnZN54Bb3OQhJtMFq1maRUyE3WblGxLwrk0Ln36q5DA+gceDy+tRz5hL7rVQPHexcQGslLDIgbzS5cUQN+6GnHtB5EMdYGAqaqTljnvCmhuFx0aRfvgHNAWhFk/9vjnW2AjFKPlr3/v01ppV4wfreZeOAurQDntvEv9g9dq2ZSFg0XGKtjzGhCd5bkCJrFqB4HEpeRW904DMBjbWz3V+jIRRVVcF9wycqFxg2Z96WnIrsgyt7O9Ake60H/DmfAY/gy1zhhrzZNiVXPnM7RRSgNiYjGNnhCG1tAfmSXtjYX5hO2o1VYypNPMATYM4bE4dRKZkRNiD7xCZUhqb7xHYdNakEMIvusnv9ZrJj7WJc74P27qoDGp3+w2OBzpBuPRAjDN32dhYJJEfM11q8K420d9X2nzKyFj8xgMvDR69mAzDD1ecjoqh1fPIC067XBL2BR6aXCIgpux9a7AunFVrPHrIiK+cEso7HYgMWUENxKQroockUz0jkckET0jO6f9+3584XVe4vZYzH2m08MgziLA4UZuCqbjpLfVD48fuDaQ0FWUotu1i2OzPopQgPmFIyYJhRrAj7FA/p4+/YBaq00sURoFUU="

script:
  - env
  - set -e
  - pip install git+https://github.com/drdoctr/doctr.git@travis-ci-dot-com
  - doctr deploy --built-docs test-html/ .
